runtime: python
env: flex
service: kritikanew1

runtime_config:
  python_version: 3.11

entrypoint: gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 120 --worker-class uvicorn.workers.UvicornWorker main:app

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

env_variables:
  TELEGRAM_BOT_TOKEN: "7833059587:AAGWCrFoYJqaIy51BHHRVtNrimJbZGTMows"
  GOOGLE_API_KEY: "AIzaSyDc6wrTkV2k4AWl72NZxET6URrXCbM8haM"
  WEBHOOK_URL: "https://kritikanew1-494584189423.europe-west1.run.app/webhook"
  PORT: "8080"
