steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kritikanew1', '.']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'kritikanew1'
    - '--image'
    - 'gcr.io/$PROJECT_ID/kritikanew1'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'TELEGRAM_BOT_TOKEN=7833059587:AAGWCrFoYJqaIy51BHHRVtNrimJbZGTMows,GOOGLE_API_KEY=AIzaSyDc6wrTkV2k4AWl72NZxET6URrXCbM8haM,WEBHOOK_URL=https://kritikanew1-494584189423.europe-west1.run.app/webhook'
    - '--port'
    - '8080'
    - '--timeout'
    - '300'
    - '--cpu'
    - '1'
    - '--memory'
    - '1Gi'
